# Generated by Django 4.0.2 on 2022-02-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animal_genus_animal_genus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='genus',
        ),
        migrations.AddField(
            model_name='animal',
            name='genus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='animals.genus'),
        ),
    ]
